// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLTwiT3UzFJnAbDrBDIBWGUX5AAZQxNF4',
    appId: '1:534816552268:web:810a78b70645f4c155cbe9',
    messagingSenderId: '534816552268',
    projectId: 'towerofhanoi-705de',
    authDomain: 'towerofhanoi-705de.firebaseapp.com',
    storageBucket: 'towerofhanoi-705de.firebasestorage.app',
    measurementId: 'G-4TNE334757',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9FlKyn3VYzZGfeSDXbYEAi7iiJAxVyo',
    appId: '1:534816552268:android:6f65b79f4ad1e8c155cbe9',
    messagingSenderId: '534816552268',
    projectId: 'towerofhanoi-705de',
    storageBucket: 'towerofhanoi-705de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0afgqYve-AryPhnhu89lNjf96BvEW_t4',
    appId: '1:534816552268:ios:b4555c3522108c7555cbe9',
    messagingSenderId: '534816552268',
    projectId: 'towerofhanoi-705de',
    storageBucket: 'towerofhanoi-705de.firebasestorage.app',
    iosBundleId: 'com.example.towerofhanoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0afgqYve-AryPhnhu89lNjf96BvEW_t4',
    appId: '1:534816552268:ios:b4555c3522108c7555cbe9',
    messagingSenderId: '534816552268',
    projectId: 'towerofhanoi-705de',
    storageBucket: 'towerofhanoi-705de.firebasestorage.app',
    iosBundleId: 'com.example.towerofhanoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLTwiT3UzFJnAbDrBDIBWGUX5AAZQxNF4',
    appId: '1:534816552268:web:048cc1d33338588655cbe9',
    messagingSenderId: '534816552268',
    projectId: 'towerofhanoi-705de',
    authDomain: 'towerofhanoi-705de.firebaseapp.com',
    storageBucket: 'towerofhanoi-705de.firebasestorage.app',
    measurementId: 'G-KRVQF24DT2',
  );
}
